# Generated by Django 4.2 on 2023-09-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='addDate',
            field=models.DateField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(blank=True, choices=[('Inspection', 'Inspection'), ('Survey', 'Survey'), ('TitleSearch', 'titleSearch'), ('TermiteInspection', 'TermiteInspection'), ('TitleInsurance', 'TitleInsurance'), ('Lawyer', 'Lawyer'), ('MortgageLoan', 'MortgageLoan'), ('MoldInspection', 'MoldInspection'), ('RadonInspection', 'RadonInspection'), ('HandyMan', 'HandyMan'), ('Other_Action_1', 'Other_Action_1'), ('Other_Action_2', 'Other_Action_2'), ('Other_Action_3', 'Other_Action_3')], default=None, help_text="What is this person's role?", max_length=17, null=True),
        ),
    ]
